# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AdvancedGameStat Class
#'
#' @field gameId 
#' @field season 
#' @field week 
#' @field team 
#' @field opponent 
#' @field offense 
#' @field defense 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AdvancedGameStat <- R6::R6Class(
  'AdvancedGameStat',
  public = list(
    `gameId` = NULL,
    `season` = NULL,
    `week` = NULL,
    `team` = NULL,
    `opponent` = NULL,
    `offense` = NULL,
    `defense` = NULL,
    initialize = function(`gameId`, `season`, `week`, `team`, `opponent`, `offense`, `defense`){
      if (!missing(`gameId`)) {
        stopifnot(is.numeric(`gameId`), length(`gameId`) == 1)
        self$`gameId` <- `gameId`
      }
      if (!missing(`season`)) {
        stopifnot(is.numeric(`season`), length(`season`) == 1)
        self$`season` <- `season`
      }
      if (!missing(`week`)) {
        stopifnot(is.numeric(`week`), length(`week`) == 1)
        self$`week` <- `week`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`opponent`)) {
        stopifnot(is.character(`opponent`), length(`opponent`) == 1)
        self$`opponent` <- `opponent`
      }
      if (!missing(`offense`)) {
        stopifnot(R6::is.R6(`offense`))
        self$`offense` <- `offense`
      }
      if (!missing(`defense`)) {
        stopifnot(R6::is.R6(`defense`))
        self$`defense` <- `defense`
      }
    },
    toJSON = function() {
      AdvancedGameStatObject <- list()
      if (!is.null(self$`gameId`)) {
        AdvancedGameStatObject[['gameId']] <- self$`gameId`
      }
      if (!is.null(self$`season`)) {
        AdvancedGameStatObject[['season']] <- self$`season`
      }
      if (!is.null(self$`week`)) {
        AdvancedGameStatObject[['week']] <- self$`week`
      }
      if (!is.null(self$`team`)) {
        AdvancedGameStatObject[['team']] <- self$`team`
      }
      if (!is.null(self$`opponent`)) {
        AdvancedGameStatObject[['opponent']] <- self$`opponent`
      }
      if (!is.null(self$`offense`)) {
        AdvancedGameStatObject[['offense']] <- self$`offense`$toJSON()
      }
      if (!is.null(self$`defense`)) {
        AdvancedGameStatObject[['defense']] <- self$`defense`$toJSON()
      }

      AdvancedGameStatObject
    },
    fromJSON = function(AdvancedGameStatJson) {
      AdvancedGameStatObject <- jsonlite::fromJSON(AdvancedGameStatJson)
      if (!is.null(AdvancedGameStatObject$`gameId`)) {
        self$`gameId` <- AdvancedGameStatObject$`gameId`
      }
      if (!is.null(AdvancedGameStatObject$`season`)) {
        self$`season` <- AdvancedGameStatObject$`season`
      }
      if (!is.null(AdvancedGameStatObject$`week`)) {
        self$`week` <- AdvancedGameStatObject$`week`
      }
      if (!is.null(AdvancedGameStatObject$`team`)) {
        self$`team` <- AdvancedGameStatObject$`team`
      }
      if (!is.null(AdvancedGameStatObject$`opponent`)) {
        self$`opponent` <- AdvancedGameStatObject$`opponent`
      }
      if (!is.null(AdvancedGameStatObject$`offense`)) {
        offenseObject <- AdvancedGameStatOffense$new()
        offenseObject$fromJSON(jsonlite::toJSON(AdvancedGameStatObject$offense, auto_unbox = TRUE))
        self$`offense` <- offenseObject
      }
      if (!is.null(AdvancedGameStatObject$`defense`)) {
        defenseObject <- AdvancedGameStatOffense$new()
        defenseObject$fromJSON(jsonlite::toJSON(AdvancedGameStatObject$defense, auto_unbox = TRUE))
        self$`defense` <- defenseObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "gameId": %d,
           "season": %d,
           "week": %d,
           "team": %s,
           "opponent": %s,
           "offense": %s,
           "defense": %s
        }',
        self$`gameId`,
        self$`season`,
        self$`week`,
        self$`team`,
        self$`opponent`,
        self$`offense`$toJSON(),
        self$`defense`$toJSON()
      )
    },
    fromJSONString = function(AdvancedGameStatJson) {
      AdvancedGameStatObject <- jsonlite::fromJSON(AdvancedGameStatJson)
      self$`gameId` <- AdvancedGameStatObject$`gameId`
      self$`season` <- AdvancedGameStatObject$`season`
      self$`week` <- AdvancedGameStatObject$`week`
      self$`team` <- AdvancedGameStatObject$`team`
      self$`opponent` <- AdvancedGameStatObject$`opponent`
      AdvancedGameStatOffenseObject <- AdvancedGameStatOffense$new()
      self$`offense` <- AdvancedGameStatOffenseObject$fromJSON(jsonlite::toJSON(AdvancedGameStatObject$offense, auto_unbox = TRUE))
      AdvancedGameStatOffenseObject <- AdvancedGameStatOffense$new()
      self$`defense` <- AdvancedGameStatOffenseObject$fromJSON(jsonlite::toJSON(AdvancedGameStatObject$defense, auto_unbox = TRUE))
    }
  )
)
