# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AdvancedSeasonStatOffenseRushingPlays Class
#'
#' @field rate 
#' @field ppa 
#' @field totalPPA 
#' @field successRate 
#' @field explosiveness 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AdvancedSeasonStatOffenseRushingPlays <- R6::R6Class(
  'AdvancedSeasonStatOffenseRushingPlays',
  public = list(
    `rate` = NULL,
    `ppa` = NULL,
    `totalPPA` = NULL,
    `successRate` = NULL,
    `explosiveness` = NULL,
    initialize = function(`rate`, `ppa`, `totalPPA`, `successRate`, `explosiveness`){
      if (!missing(`rate`)) {
        self$`rate` <- `rate`
      }
      if (!missing(`ppa`)) {
        self$`ppa` <- `ppa`
      }
      if (!missing(`totalPPA`)) {
        self$`totalPPA` <- `totalPPA`
      }
      if (!missing(`successRate`)) {
        self$`successRate` <- `successRate`
      }
      if (!missing(`explosiveness`)) {
        self$`explosiveness` <- `explosiveness`
      }
    },
    toJSON = function() {
      AdvancedSeasonStatOffenseRushingPlaysObject <- list()
      if (!is.null(self$`rate`)) {
        AdvancedSeasonStatOffenseRushingPlaysObject[['rate']] <- self$`rate`
      }
      if (!is.null(self$`ppa`)) {
        AdvancedSeasonStatOffenseRushingPlaysObject[['ppa']] <- self$`ppa`
      }
      if (!is.null(self$`totalPPA`)) {
        AdvancedSeasonStatOffenseRushingPlaysObject[['totalPPA']] <- self$`totalPPA`
      }
      if (!is.null(self$`successRate`)) {
        AdvancedSeasonStatOffenseRushingPlaysObject[['successRate']] <- self$`successRate`
      }
      if (!is.null(self$`explosiveness`)) {
        AdvancedSeasonStatOffenseRushingPlaysObject[['explosiveness']] <- self$`explosiveness`
      }

      AdvancedSeasonStatOffenseRushingPlaysObject
    },
    fromJSON = function(AdvancedSeasonStatOffenseRushingPlaysJson) {
      AdvancedSeasonStatOffenseRushingPlaysObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseRushingPlaysJson)
      if (!is.null(AdvancedSeasonStatOffenseRushingPlaysObject$`rate`)) {
        self$`rate` <- AdvancedSeasonStatOffenseRushingPlaysObject$`rate`
      }
      if (!is.null(AdvancedSeasonStatOffenseRushingPlaysObject$`ppa`)) {
        self$`ppa` <- AdvancedSeasonStatOffenseRushingPlaysObject$`ppa`
      }
      if (!is.null(AdvancedSeasonStatOffenseRushingPlaysObject$`totalPPA`)) {
        self$`totalPPA` <- AdvancedSeasonStatOffenseRushingPlaysObject$`totalPPA`
      }
      if (!is.null(AdvancedSeasonStatOffenseRushingPlaysObject$`successRate`)) {
        self$`successRate` <- AdvancedSeasonStatOffenseRushingPlaysObject$`successRate`
      }
      if (!is.null(AdvancedSeasonStatOffenseRushingPlaysObject$`explosiveness`)) {
        self$`explosiveness` <- AdvancedSeasonStatOffenseRushingPlaysObject$`explosiveness`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rate": %s,
           "ppa": %s,
           "totalPPA": %s,
           "successRate": %s,
           "explosiveness": %s
        }',
        self$`rate`,
        self$`ppa`,
        self$`totalPPA`,
        self$`successRate`,
        self$`explosiveness`
      )
    },
    fromJSONString = function(AdvancedSeasonStatOffenseRushingPlaysJson) {
      AdvancedSeasonStatOffenseRushingPlaysObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseRushingPlaysJson)
      self$`rate` <- AdvancedSeasonStatOffenseRushingPlaysObject$`rate`
      self$`ppa` <- AdvancedSeasonStatOffenseRushingPlaysObject$`ppa`
      self$`totalPPA` <- AdvancedSeasonStatOffenseRushingPlaysObject$`totalPPA`
      self$`successRate` <- AdvancedSeasonStatOffenseRushingPlaysObject$`successRate`
      self$`explosiveness` <- AdvancedSeasonStatOffenseRushingPlaysObject$`explosiveness`
    }
  )
)
