# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AdvancedSeasonStatOffenseStandardDowns Class
#'
#' @field rate 
#' @field ppa 
#' @field successRate 
#' @field explosiveness 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AdvancedSeasonStatOffenseStandardDowns <- R6::R6Class(
  'AdvancedSeasonStatOffenseStandardDowns',
  public = list(
    `rate` = NULL,
    `ppa` = NULL,
    `successRate` = NULL,
    `explosiveness` = NULL,
    initialize = function(`rate`, `ppa`, `successRate`, `explosiveness`){
      if (!missing(`rate`)) {
        self$`rate` <- `rate`
      }
      if (!missing(`ppa`)) {
        self$`ppa` <- `ppa`
      }
      if (!missing(`successRate`)) {
        self$`successRate` <- `successRate`
      }
      if (!missing(`explosiveness`)) {
        self$`explosiveness` <- `explosiveness`
      }
    },
    toJSON = function() {
      AdvancedSeasonStatOffenseStandardDownsObject <- list()
      if (!is.null(self$`rate`)) {
        AdvancedSeasonStatOffenseStandardDownsObject[['rate']] <- self$`rate`
      }
      if (!is.null(self$`ppa`)) {
        AdvancedSeasonStatOffenseStandardDownsObject[['ppa']] <- self$`ppa`
      }
      if (!is.null(self$`successRate`)) {
        AdvancedSeasonStatOffenseStandardDownsObject[['successRate']] <- self$`successRate`
      }
      if (!is.null(self$`explosiveness`)) {
        AdvancedSeasonStatOffenseStandardDownsObject[['explosiveness']] <- self$`explosiveness`
      }

      AdvancedSeasonStatOffenseStandardDownsObject
    },
    fromJSON = function(AdvancedSeasonStatOffenseStandardDownsJson) {
      AdvancedSeasonStatOffenseStandardDownsObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseStandardDownsJson)
      if (!is.null(AdvancedSeasonStatOffenseStandardDownsObject$`rate`)) {
        self$`rate` <- AdvancedSeasonStatOffenseStandardDownsObject$`rate`
      }
      if (!is.null(AdvancedSeasonStatOffenseStandardDownsObject$`ppa`)) {
        self$`ppa` <- AdvancedSeasonStatOffenseStandardDownsObject$`ppa`
      }
      if (!is.null(AdvancedSeasonStatOffenseStandardDownsObject$`successRate`)) {
        self$`successRate` <- AdvancedSeasonStatOffenseStandardDownsObject$`successRate`
      }
      if (!is.null(AdvancedSeasonStatOffenseStandardDownsObject$`explosiveness`)) {
        self$`explosiveness` <- AdvancedSeasonStatOffenseStandardDownsObject$`explosiveness`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rate": %s,
           "ppa": %s,
           "successRate": %s,
           "explosiveness": %s
        }',
        self$`rate`,
        self$`ppa`,
        self$`successRate`,
        self$`explosiveness`
      )
    },
    fromJSONString = function(AdvancedSeasonStatOffenseStandardDownsJson) {
      AdvancedSeasonStatOffenseStandardDownsObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseStandardDownsJson)
      self$`rate` <- AdvancedSeasonStatOffenseStandardDownsObject$`rate`
      self$`ppa` <- AdvancedSeasonStatOffenseStandardDownsObject$`ppa`
      self$`successRate` <- AdvancedSeasonStatOffenseStandardDownsObject$`successRate`
      self$`explosiveness` <- AdvancedSeasonStatOffenseStandardDownsObject$`explosiveness`
    }
  )
)
