# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AdvancedSeasonStatOffenseFieldPosition Class
#'
#' @field averageStart 
#' @field averagePredictedPoints 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AdvancedSeasonStatOffenseFieldPosition <- R6::R6Class(
  'AdvancedSeasonStatOffenseFieldPosition',
  public = list(
    `averageStart` = NULL,
    `averagePredictedPoints` = NULL,
    initialize = function(`averageStart`, `averagePredictedPoints`){
      if (!missing(`averageStart`)) {
        self$`averageStart` <- `averageStart`
      }
      if (!missing(`averagePredictedPoints`)) {
        self$`averagePredictedPoints` <- `averagePredictedPoints`
      }
    },
    toJSON = function() {
      AdvancedSeasonStatOffenseFieldPositionObject <- list()
      if (!is.null(self$`averageStart`)) {
        AdvancedSeasonStatOffenseFieldPositionObject[['averageStart']] <- self$`averageStart`
      }
      if (!is.null(self$`averagePredictedPoints`)) {
        AdvancedSeasonStatOffenseFieldPositionObject[['averagePredictedPoints']] <- self$`averagePredictedPoints`
      }

      AdvancedSeasonStatOffenseFieldPositionObject
    },
    fromJSON = function(AdvancedSeasonStatOffenseFieldPositionJson) {
      AdvancedSeasonStatOffenseFieldPositionObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseFieldPositionJson)
      if (!is.null(AdvancedSeasonStatOffenseFieldPositionObject$`averageStart`)) {
        self$`averageStart` <- AdvancedSeasonStatOffenseFieldPositionObject$`averageStart`
      }
      if (!is.null(AdvancedSeasonStatOffenseFieldPositionObject$`averagePredictedPoints`)) {
        self$`averagePredictedPoints` <- AdvancedSeasonStatOffenseFieldPositionObject$`averagePredictedPoints`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "averageStart": %s,
           "averagePredictedPoints": %s
        }',
        self$`averageStart`,
        self$`averagePredictedPoints`
      )
    },
    fromJSONString = function(AdvancedSeasonStatOffenseFieldPositionJson) {
      AdvancedSeasonStatOffenseFieldPositionObject <- jsonlite::fromJSON(AdvancedSeasonStatOffenseFieldPositionJson)
      self$`averageStart` <- AdvancedSeasonStatOffenseFieldPositionObject$`averageStart`
      self$`averagePredictedPoints` <- AdvancedSeasonStatOffenseFieldPositionObject$`averagePredictedPoints`
    }
  )
)
