# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AdvancedSeasonStat Class
#'
#' @field season 
#' @field team 
#' @field conference 
#' @field offense 
#' @field defense 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AdvancedSeasonStat <- R6::R6Class(
  'AdvancedSeasonStat',
  public = list(
    `season` = NULL,
    `team` = NULL,
    `conference` = NULL,
    `offense` = NULL,
    `defense` = NULL,
    initialize = function(`season`, `team`, `conference`, `offense`, `defense`){
      if (!missing(`season`)) {
        stopifnot(is.numeric(`season`), length(`season`) == 1)
        self$`season` <- `season`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`conference`)) {
        stopifnot(is.character(`conference`), length(`conference`) == 1)
        self$`conference` <- `conference`
      }
      if (!missing(`offense`)) {
        stopifnot(R6::is.R6(`offense`))
        self$`offense` <- `offense`
      }
      if (!missing(`defense`)) {
        stopifnot(R6::is.R6(`defense`))
        self$`defense` <- `defense`
      }
    },
    toJSON = function() {
      AdvancedSeasonStatObject <- list()
      if (!is.null(self$`season`)) {
        AdvancedSeasonStatObject[['season']] <- self$`season`
      }
      if (!is.null(self$`team`)) {
        AdvancedSeasonStatObject[['team']] <- self$`team`
      }
      if (!is.null(self$`conference`)) {
        AdvancedSeasonStatObject[['conference']] <- self$`conference`
      }
      if (!is.null(self$`offense`)) {
        AdvancedSeasonStatObject[['offense']] <- self$`offense`$toJSON()
      }
      if (!is.null(self$`defense`)) {
        AdvancedSeasonStatObject[['defense']] <- self$`defense`$toJSON()
      }

      AdvancedSeasonStatObject
    },
    fromJSON = function(AdvancedSeasonStatJson) {
      AdvancedSeasonStatObject <- jsonlite::fromJSON(AdvancedSeasonStatJson)
      if (!is.null(AdvancedSeasonStatObject$`season`)) {
        self$`season` <- AdvancedSeasonStatObject$`season`
      }
      if (!is.null(AdvancedSeasonStatObject$`team`)) {
        self$`team` <- AdvancedSeasonStatObject$`team`
      }
      if (!is.null(AdvancedSeasonStatObject$`conference`)) {
        self$`conference` <- AdvancedSeasonStatObject$`conference`
      }
      if (!is.null(AdvancedSeasonStatObject$`offense`)) {
        offenseObject <- AdvancedSeasonStatOffense$new()
        offenseObject$fromJSON(jsonlite::toJSON(AdvancedSeasonStatObject$offense, auto_unbox = TRUE))
        self$`offense` <- offenseObject
      }
      if (!is.null(AdvancedSeasonStatObject$`defense`)) {
        defenseObject <- AdvancedSeasonStatOffense$new()
        defenseObject$fromJSON(jsonlite::toJSON(AdvancedSeasonStatObject$defense, auto_unbox = TRUE))
        self$`defense` <- defenseObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "season": %d,
           "team": %s,
           "conference": %s,
           "offense": %s,
           "defense": %s
        }',
        self$`season`,
        self$`team`,
        self$`conference`,
        self$`offense`$toJSON(),
        self$`defense`$toJSON()
      )
    },
    fromJSONString = function(AdvancedSeasonStatJson) {
      AdvancedSeasonStatObject <- jsonlite::fromJSON(AdvancedSeasonStatJson)
      self$`season` <- AdvancedSeasonStatObject$`season`
      self$`team` <- AdvancedSeasonStatObject$`team`
      self$`conference` <- AdvancedSeasonStatObject$`conference`
      AdvancedSeasonStatOffenseObject <- AdvancedSeasonStatOffense$new()
      self$`offense` <- AdvancedSeasonStatOffenseObject$fromJSON(jsonlite::toJSON(AdvancedSeasonStatObject$offense, auto_unbox = TRUE))
      AdvancedSeasonStatOffenseObject <- AdvancedSeasonStatOffense$new()
      self$`defense` <- AdvancedSeasonStatOffenseObject$fromJSON(jsonlite::toJSON(AdvancedSeasonStatObject$defense, auto_unbox = TRUE))
    }
  )
)
