# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BoxScoreTeamsPpa Class
#'
#' @field team 
#' @field plays 
#' @field overall 
#' @field passing 
#' @field rushing 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BoxScoreTeamsPpa <- R6::R6Class(
  'BoxScoreTeamsPpa',
  public = list(
    `team` = NULL,
    `plays` = NULL,
    `overall` = NULL,
    `passing` = NULL,
    `rushing` = NULL,
    initialize = function(`team`, `plays`, `overall`, `passing`, `rushing`){
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`plays`)) {
        self$`plays` <- `plays`
      }
      if (!missing(`overall`)) {
        stopifnot(R6::is.R6(`overall`))
        self$`overall` <- `overall`
      }
      if (!missing(`passing`)) {
        stopifnot(R6::is.R6(`passing`))
        self$`passing` <- `passing`
      }
      if (!missing(`rushing`)) {
        stopifnot(R6::is.R6(`rushing`))
        self$`rushing` <- `rushing`
      }
    },
    toJSON = function() {
      BoxScoreTeamsPpaObject <- list()
      if (!is.null(self$`team`)) {
        BoxScoreTeamsPpaObject[['team']] <- self$`team`
      }
      if (!is.null(self$`plays`)) {
        BoxScoreTeamsPpaObject[['plays']] <- self$`plays`
      }
      if (!is.null(self$`overall`)) {
        BoxScoreTeamsPpaObject[['overall']] <- self$`overall`$toJSON()
      }
      if (!is.null(self$`passing`)) {
        BoxScoreTeamsPpaObject[['passing']] <- self$`passing`$toJSON()
      }
      if (!is.null(self$`rushing`)) {
        BoxScoreTeamsPpaObject[['rushing']] <- self$`rushing`$toJSON()
      }

      BoxScoreTeamsPpaObject
    },
    fromJSON = function(BoxScoreTeamsPpaJson) {
      BoxScoreTeamsPpaObject <- jsonlite::fromJSON(BoxScoreTeamsPpaJson)
      if (!is.null(BoxScoreTeamsPpaObject$`team`)) {
        self$`team` <- BoxScoreTeamsPpaObject$`team`
      }
      if (!is.null(BoxScoreTeamsPpaObject$`plays`)) {
        self$`plays` <- BoxScoreTeamsPpaObject$`plays`
      }
      if (!is.null(BoxScoreTeamsPpaObject$`overall`)) {
        overallObject <- BoxScoreTeamsOverall$new()
        overallObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$overall, auto_unbox = TRUE))
        self$`overall` <- overallObject
      }
      if (!is.null(BoxScoreTeamsPpaObject$`passing`)) {
        passingObject <- BoxScoreTeamsOverall$new()
        passingObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$passing, auto_unbox = TRUE))
        self$`passing` <- passingObject
      }
      if (!is.null(BoxScoreTeamsPpaObject$`rushing`)) {
        rushingObject <- BoxScoreTeamsOverall$new()
        rushingObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$rushing, auto_unbox = TRUE))
        self$`rushing` <- rushingObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "team": %s,
           "plays": %s,
           "overall": %s,
           "passing": %s,
           "rushing": %s
        }',
        self$`team`,
        self$`plays`,
        self$`overall`$toJSON(),
        self$`passing`$toJSON(),
        self$`rushing`$toJSON()
      )
    },
    fromJSONString = function(BoxScoreTeamsPpaJson) {
      BoxScoreTeamsPpaObject <- jsonlite::fromJSON(BoxScoreTeamsPpaJson)
      self$`team` <- BoxScoreTeamsPpaObject$`team`
      self$`plays` <- BoxScoreTeamsPpaObject$`plays`
      BoxScoreTeamsOverallObject <- BoxScoreTeamsOverall$new()
      self$`overall` <- BoxScoreTeamsOverallObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$overall, auto_unbox = TRUE))
      BoxScoreTeamsOverallObject <- BoxScoreTeamsOverall$new()
      self$`passing` <- BoxScoreTeamsOverallObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$passing, auto_unbox = TRUE))
      BoxScoreTeamsOverallObject <- BoxScoreTeamsOverall$new()
      self$`rushing` <- BoxScoreTeamsOverallObject$fromJSON(jsonlite::toJSON(BoxScoreTeamsPpaObject$rushing, auto_unbox = TRUE))
    }
  )
)
