# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BoxScoreTeamsFieldPosition Class
#'
#' @field team 
#' @field averageStart 
#' @field averageStartingPredictedPoints 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BoxScoreTeamsFieldPosition <- R6::R6Class(
  'BoxScoreTeamsFieldPosition',
  public = list(
    `team` = NULL,
    `averageStart` = NULL,
    `averageStartingPredictedPoints` = NULL,
    initialize = function(`team`, `averageStart`, `averageStartingPredictedPoints`){
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`averageStart`)) {
        self$`averageStart` <- `averageStart`
      }
      if (!missing(`averageStartingPredictedPoints`)) {
        self$`averageStartingPredictedPoints` <- `averageStartingPredictedPoints`
      }
    },
    toJSON = function() {
      BoxScoreTeamsFieldPositionObject <- list()
      if (!is.null(self$`team`)) {
        BoxScoreTeamsFieldPositionObject[['team']] <- self$`team`
      }
      if (!is.null(self$`averageStart`)) {
        BoxScoreTeamsFieldPositionObject[['averageStart']] <- self$`averageStart`
      }
      if (!is.null(self$`averageStartingPredictedPoints`)) {
        BoxScoreTeamsFieldPositionObject[['averageStartingPredictedPoints']] <- self$`averageStartingPredictedPoints`
      }

      BoxScoreTeamsFieldPositionObject
    },
    fromJSON = function(BoxScoreTeamsFieldPositionJson) {
      BoxScoreTeamsFieldPositionObject <- jsonlite::fromJSON(BoxScoreTeamsFieldPositionJson)
      if (!is.null(BoxScoreTeamsFieldPositionObject$`team`)) {
        self$`team` <- BoxScoreTeamsFieldPositionObject$`team`
      }
      if (!is.null(BoxScoreTeamsFieldPositionObject$`averageStart`)) {
        self$`averageStart` <- BoxScoreTeamsFieldPositionObject$`averageStart`
      }
      if (!is.null(BoxScoreTeamsFieldPositionObject$`averageStartingPredictedPoints`)) {
        self$`averageStartingPredictedPoints` <- BoxScoreTeamsFieldPositionObject$`averageStartingPredictedPoints`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "team": %s,
           "averageStart": %s,
           "averageStartingPredictedPoints": %s
        }',
        self$`team`,
        self$`averageStart`,
        self$`averageStartingPredictedPoints`
      )
    },
    fromJSONString = function(BoxScoreTeamsFieldPositionJson) {
      BoxScoreTeamsFieldPositionObject <- jsonlite::fromJSON(BoxScoreTeamsFieldPositionJson)
      self$`team` <- BoxScoreTeamsFieldPositionObject$`team`
      self$`averageStart` <- BoxScoreTeamsFieldPositionObject$`averageStart`
      self$`averageStartingPredictedPoints` <- BoxScoreTeamsFieldPositionObject$`averageStartingPredictedPoints`
    }
  )
)
