# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BoxScorePlayersUsage Class
#'
#' @field player 
#' @field team 
#' @field position 
#' @field total 
#' @field quarter1 
#' @field quarter2 
#' @field quarter3 
#' @field quarter4 
#' @field rushing 
#' @field passing 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BoxScorePlayersUsage <- R6::R6Class(
  'BoxScorePlayersUsage',
  public = list(
    `player` = NULL,
    `team` = NULL,
    `position` = NULL,
    `total` = NULL,
    `quarter1` = NULL,
    `quarter2` = NULL,
    `quarter3` = NULL,
    `quarter4` = NULL,
    `rushing` = NULL,
    `passing` = NULL,
    initialize = function(`player`, `team`, `position`, `total`, `quarter1`, `quarter2`, `quarter3`, `quarter4`, `rushing`, `passing`){
      if (!missing(`player`)) {
        stopifnot(is.character(`player`), length(`player`) == 1)
        self$`player` <- `player`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`position`)) {
        stopifnot(is.character(`position`), length(`position`) == 1)
        self$`position` <- `position`
      }
      if (!missing(`total`)) {
        self$`total` <- `total`
      }
      if (!missing(`quarter1`)) {
        self$`quarter1` <- `quarter1`
      }
      if (!missing(`quarter2`)) {
        self$`quarter2` <- `quarter2`
      }
      if (!missing(`quarter3`)) {
        self$`quarter3` <- `quarter3`
      }
      if (!missing(`quarter4`)) {
        self$`quarter4` <- `quarter4`
      }
      if (!missing(`rushing`)) {
        self$`rushing` <- `rushing`
      }
      if (!missing(`passing`)) {
        self$`passing` <- `passing`
      }
    },
    toJSON = function() {
      BoxScorePlayersUsageObject <- list()
      if (!is.null(self$`player`)) {
        BoxScorePlayersUsageObject[['player']] <- self$`player`
      }
      if (!is.null(self$`team`)) {
        BoxScorePlayersUsageObject[['team']] <- self$`team`
      }
      if (!is.null(self$`position`)) {
        BoxScorePlayersUsageObject[['position']] <- self$`position`
      }
      if (!is.null(self$`total`)) {
        BoxScorePlayersUsageObject[['total']] <- self$`total`
      }
      if (!is.null(self$`quarter1`)) {
        BoxScorePlayersUsageObject[['quarter1']] <- self$`quarter1`
      }
      if (!is.null(self$`quarter2`)) {
        BoxScorePlayersUsageObject[['quarter2']] <- self$`quarter2`
      }
      if (!is.null(self$`quarter3`)) {
        BoxScorePlayersUsageObject[['quarter3']] <- self$`quarter3`
      }
      if (!is.null(self$`quarter4`)) {
        BoxScorePlayersUsageObject[['quarter4']] <- self$`quarter4`
      }
      if (!is.null(self$`rushing`)) {
        BoxScorePlayersUsageObject[['rushing']] <- self$`rushing`
      }
      if (!is.null(self$`passing`)) {
        BoxScorePlayersUsageObject[['passing']] <- self$`passing`
      }

      BoxScorePlayersUsageObject
    },
    fromJSON = function(BoxScorePlayersUsageJson) {
      BoxScorePlayersUsageObject <- jsonlite::fromJSON(BoxScorePlayersUsageJson)
      if (!is.null(BoxScorePlayersUsageObject$`player`)) {
        self$`player` <- BoxScorePlayersUsageObject$`player`
      }
      if (!is.null(BoxScorePlayersUsageObject$`team`)) {
        self$`team` <- BoxScorePlayersUsageObject$`team`
      }
      if (!is.null(BoxScorePlayersUsageObject$`position`)) {
        self$`position` <- BoxScorePlayersUsageObject$`position`
      }
      if (!is.null(BoxScorePlayersUsageObject$`total`)) {
        self$`total` <- BoxScorePlayersUsageObject$`total`
      }
      if (!is.null(BoxScorePlayersUsageObject$`quarter1`)) {
        self$`quarter1` <- BoxScorePlayersUsageObject$`quarter1`
      }
      if (!is.null(BoxScorePlayersUsageObject$`quarter2`)) {
        self$`quarter2` <- BoxScorePlayersUsageObject$`quarter2`
      }
      if (!is.null(BoxScorePlayersUsageObject$`quarter3`)) {
        self$`quarter3` <- BoxScorePlayersUsageObject$`quarter3`
      }
      if (!is.null(BoxScorePlayersUsageObject$`quarter4`)) {
        self$`quarter4` <- BoxScorePlayersUsageObject$`quarter4`
      }
      if (!is.null(BoxScorePlayersUsageObject$`rushing`)) {
        self$`rushing` <- BoxScorePlayersUsageObject$`rushing`
      }
      if (!is.null(BoxScorePlayersUsageObject$`passing`)) {
        self$`passing` <- BoxScorePlayersUsageObject$`passing`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "player": %s,
           "team": %s,
           "position": %s,
           "total": %s,
           "quarter1": %s,
           "quarter2": %s,
           "quarter3": %s,
           "quarter4": %s,
           "rushing": %s,
           "passing": %s
        }',
        self$`player`,
        self$`team`,
        self$`position`,
        self$`total`,
        self$`quarter1`,
        self$`quarter2`,
        self$`quarter3`,
        self$`quarter4`,
        self$`rushing`,
        self$`passing`
      )
    },
    fromJSONString = function(BoxScorePlayersUsageJson) {
      BoxScorePlayersUsageObject <- jsonlite::fromJSON(BoxScorePlayersUsageJson)
      self$`player` <- BoxScorePlayersUsageObject$`player`
      self$`team` <- BoxScorePlayersUsageObject$`team`
      self$`position` <- BoxScorePlayersUsageObject$`position`
      self$`total` <- BoxScorePlayersUsageObject$`total`
      self$`quarter1` <- BoxScorePlayersUsageObject$`quarter1`
      self$`quarter2` <- BoxScorePlayersUsageObject$`quarter2`
      self$`quarter3` <- BoxScorePlayersUsageObject$`quarter3`
      self$`quarter4` <- BoxScorePlayersUsageObject$`quarter4`
      self$`rushing` <- BoxScorePlayersUsageObject$`rushing`
      self$`passing` <- BoxScorePlayersUsageObject$`passing`
    }
  )
)
