# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BoxScoreTeamsRushing Class
#'
#' @field team 
#' @field powerSuccess 
#' @field stuffRate 
#' @field lineYards 
#' @field lineYardsAverage 
#' @field secondLevelYards 
#' @field secondLevelYardsAverage 
#' @field openFieldYards 
#' @field openFieldYardsAverage 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BoxScoreTeamsRushing <- R6::R6Class(
  'BoxScoreTeamsRushing',
  public = list(
    `team` = NULL,
    `powerSuccess` = NULL,
    `stuffRate` = NULL,
    `lineYards` = NULL,
    `lineYardsAverage` = NULL,
    `secondLevelYards` = NULL,
    `secondLevelYardsAverage` = NULL,
    `openFieldYards` = NULL,
    `openFieldYardsAverage` = NULL,
    initialize = function(`team`, `powerSuccess`, `stuffRate`, `lineYards`, `lineYardsAverage`, `secondLevelYards`, `secondLevelYardsAverage`, `openFieldYards`, `openFieldYardsAverage`){
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`powerSuccess`)) {
        self$`powerSuccess` <- `powerSuccess`
      }
      if (!missing(`stuffRate`)) {
        self$`stuffRate` <- `stuffRate`
      }
      if (!missing(`lineYards`)) {
        self$`lineYards` <- `lineYards`
      }
      if (!missing(`lineYardsAverage`)) {
        self$`lineYardsAverage` <- `lineYardsAverage`
      }
      if (!missing(`secondLevelYards`)) {
        stopifnot(is.numeric(`secondLevelYards`), length(`secondLevelYards`) == 1)
        self$`secondLevelYards` <- `secondLevelYards`
      }
      if (!missing(`secondLevelYardsAverage`)) {
        self$`secondLevelYardsAverage` <- `secondLevelYardsAverage`
      }
      if (!missing(`openFieldYards`)) {
        stopifnot(is.numeric(`openFieldYards`), length(`openFieldYards`) == 1)
        self$`openFieldYards` <- `openFieldYards`
      }
      if (!missing(`openFieldYardsAverage`)) {
        self$`openFieldYardsAverage` <- `openFieldYardsAverage`
      }
    },
    toJSON = function() {
      BoxScoreTeamsRushingObject <- list()
      if (!is.null(self$`team`)) {
        BoxScoreTeamsRushingObject[['team']] <- self$`team`
      }
      if (!is.null(self$`powerSuccess`)) {
        BoxScoreTeamsRushingObject[['powerSuccess']] <- self$`powerSuccess`
      }
      if (!is.null(self$`stuffRate`)) {
        BoxScoreTeamsRushingObject[['stuffRate']] <- self$`stuffRate`
      }
      if (!is.null(self$`lineYards`)) {
        BoxScoreTeamsRushingObject[['lineYards']] <- self$`lineYards`
      }
      if (!is.null(self$`lineYardsAverage`)) {
        BoxScoreTeamsRushingObject[['lineYardsAverage']] <- self$`lineYardsAverage`
      }
      if (!is.null(self$`secondLevelYards`)) {
        BoxScoreTeamsRushingObject[['secondLevelYards']] <- self$`secondLevelYards`
      }
      if (!is.null(self$`secondLevelYardsAverage`)) {
        BoxScoreTeamsRushingObject[['secondLevelYardsAverage']] <- self$`secondLevelYardsAverage`
      }
      if (!is.null(self$`openFieldYards`)) {
        BoxScoreTeamsRushingObject[['openFieldYards']] <- self$`openFieldYards`
      }
      if (!is.null(self$`openFieldYardsAverage`)) {
        BoxScoreTeamsRushingObject[['openFieldYardsAverage']] <- self$`openFieldYardsAverage`
      }

      BoxScoreTeamsRushingObject
    },
    fromJSON = function(BoxScoreTeamsRushingJson) {
      BoxScoreTeamsRushingObject <- jsonlite::fromJSON(BoxScoreTeamsRushingJson)
      if (!is.null(BoxScoreTeamsRushingObject$`team`)) {
        self$`team` <- BoxScoreTeamsRushingObject$`team`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`powerSuccess`)) {
        self$`powerSuccess` <- BoxScoreTeamsRushingObject$`powerSuccess`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`stuffRate`)) {
        self$`stuffRate` <- BoxScoreTeamsRushingObject$`stuffRate`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`lineYards`)) {
        self$`lineYards` <- BoxScoreTeamsRushingObject$`lineYards`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`lineYardsAverage`)) {
        self$`lineYardsAverage` <- BoxScoreTeamsRushingObject$`lineYardsAverage`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`secondLevelYards`)) {
        self$`secondLevelYards` <- BoxScoreTeamsRushingObject$`secondLevelYards`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`secondLevelYardsAverage`)) {
        self$`secondLevelYardsAverage` <- BoxScoreTeamsRushingObject$`secondLevelYardsAverage`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`openFieldYards`)) {
        self$`openFieldYards` <- BoxScoreTeamsRushingObject$`openFieldYards`
      }
      if (!is.null(BoxScoreTeamsRushingObject$`openFieldYardsAverage`)) {
        self$`openFieldYardsAverage` <- BoxScoreTeamsRushingObject$`openFieldYardsAverage`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "team": %s,
           "powerSuccess": %s,
           "stuffRate": %s,
           "lineYards": %s,
           "lineYardsAverage": %s,
           "secondLevelYards": %d,
           "secondLevelYardsAverage": %s,
           "openFieldYards": %d,
           "openFieldYardsAverage": %s
        }',
        self$`team`,
        self$`powerSuccess`,
        self$`stuffRate`,
        self$`lineYards`,
        self$`lineYardsAverage`,
        self$`secondLevelYards`,
        self$`secondLevelYardsAverage`,
        self$`openFieldYards`,
        self$`openFieldYardsAverage`
      )
    },
    fromJSONString = function(BoxScoreTeamsRushingJson) {
      BoxScoreTeamsRushingObject <- jsonlite::fromJSON(BoxScoreTeamsRushingJson)
      self$`team` <- BoxScoreTeamsRushingObject$`team`
      self$`powerSuccess` <- BoxScoreTeamsRushingObject$`powerSuccess`
      self$`stuffRate` <- BoxScoreTeamsRushingObject$`stuffRate`
      self$`lineYards` <- BoxScoreTeamsRushingObject$`lineYards`
      self$`lineYardsAverage` <- BoxScoreTeamsRushingObject$`lineYardsAverage`
      self$`secondLevelYards` <- BoxScoreTeamsRushingObject$`secondLevelYards`
      self$`secondLevelYardsAverage` <- BoxScoreTeamsRushingObject$`secondLevelYardsAverage`
      self$`openFieldYards` <- BoxScoreTeamsRushingObject$`openFieldYards`
      self$`openFieldYardsAverage` <- BoxScoreTeamsRushingObject$`openFieldYardsAverage`
    }
  )
)
