# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Coaches operations
#' @description swagger.Coaches
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_coaches Coaching records and history
#'
#' }
#'
#' @export
CoachesApi <- R6::R6Class(
  'CoachesApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_coaches = function(first_name, last_name, team, year, min_year, max_year, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`first_name`)) {
        queryParams['firstName'] <- first_name
      }

      if (!missing(`last_name`)) {
        queryParams['lastName'] <- last_name
      }

      if (!missing(`team`)) {
        queryParams['team'] <- team
      }

      if (!missing(`year`)) {
        queryParams['year'] <- year
      }

      if (!missing(`min_year`)) {
        queryParams['minYear'] <- min_year
      }

      if (!missing(`max_year`)) {
        queryParams['maxYear'] <- max_year
      }

      urlPath <- "/coaches"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- InlineResponse200$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
