# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConferenceSPRatingDefense Class
#'
#' @field rating 
#' @field success 
#' @field explosiveness 
#' @field rushing 
#' @field pasing 
#' @field standardDowns 
#' @field passingDowns 
#' @field havoc 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConferenceSPRatingDefense <- R6::R6Class(
  'ConferenceSPRatingDefense',
  public = list(
    `rating` = NULL,
    `success` = NULL,
    `explosiveness` = NULL,
    `rushing` = NULL,
    `pasing` = NULL,
    `standardDowns` = NULL,
    `passingDowns` = NULL,
    `havoc` = NULL,
    initialize = function(`rating`, `success`, `explosiveness`, `rushing`, `pasing`, `standardDowns`, `passingDowns`, `havoc`){
      if (!missing(`rating`)) {
        self$`rating` <- `rating`
      }
      if (!missing(`success`)) {
        self$`success` <- `success`
      }
      if (!missing(`explosiveness`)) {
        self$`explosiveness` <- `explosiveness`
      }
      if (!missing(`rushing`)) {
        self$`rushing` <- `rushing`
      }
      if (!missing(`pasing`)) {
        self$`pasing` <- `pasing`
      }
      if (!missing(`standardDowns`)) {
        self$`standardDowns` <- `standardDowns`
      }
      if (!missing(`passingDowns`)) {
        self$`passingDowns` <- `passingDowns`
      }
      if (!missing(`havoc`)) {
        stopifnot(R6::is.R6(`havoc`))
        self$`havoc` <- `havoc`
      }
    },
    toJSON = function() {
      ConferenceSPRatingDefenseObject <- list()
      if (!is.null(self$`rating`)) {
        ConferenceSPRatingDefenseObject[['rating']] <- self$`rating`
      }
      if (!is.null(self$`success`)) {
        ConferenceSPRatingDefenseObject[['success']] <- self$`success`
      }
      if (!is.null(self$`explosiveness`)) {
        ConferenceSPRatingDefenseObject[['explosiveness']] <- self$`explosiveness`
      }
      if (!is.null(self$`rushing`)) {
        ConferenceSPRatingDefenseObject[['rushing']] <- self$`rushing`
      }
      if (!is.null(self$`pasing`)) {
        ConferenceSPRatingDefenseObject[['pasing']] <- self$`pasing`
      }
      if (!is.null(self$`standardDowns`)) {
        ConferenceSPRatingDefenseObject[['standardDowns']] <- self$`standardDowns`
      }
      if (!is.null(self$`passingDowns`)) {
        ConferenceSPRatingDefenseObject[['passingDowns']] <- self$`passingDowns`
      }
      if (!is.null(self$`havoc`)) {
        ConferenceSPRatingDefenseObject[['havoc']] <- self$`havoc`$toJSON()
      }

      ConferenceSPRatingDefenseObject
    },
    fromJSON = function(ConferenceSPRatingDefenseJson) {
      ConferenceSPRatingDefenseObject <- jsonlite::fromJSON(ConferenceSPRatingDefenseJson)
      if (!is.null(ConferenceSPRatingDefenseObject$`rating`)) {
        self$`rating` <- ConferenceSPRatingDefenseObject$`rating`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`success`)) {
        self$`success` <- ConferenceSPRatingDefenseObject$`success`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`explosiveness`)) {
        self$`explosiveness` <- ConferenceSPRatingDefenseObject$`explosiveness`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`rushing`)) {
        self$`rushing` <- ConferenceSPRatingDefenseObject$`rushing`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`pasing`)) {
        self$`pasing` <- ConferenceSPRatingDefenseObject$`pasing`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`standardDowns`)) {
        self$`standardDowns` <- ConferenceSPRatingDefenseObject$`standardDowns`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`passingDowns`)) {
        self$`passingDowns` <- ConferenceSPRatingDefenseObject$`passingDowns`
      }
      if (!is.null(ConferenceSPRatingDefenseObject$`havoc`)) {
        havocObject <- TeamSPRatingDefenseHavoc$new()
        havocObject$fromJSON(jsonlite::toJSON(ConferenceSPRatingDefenseObject$havoc, auto_unbox = TRUE))
        self$`havoc` <- havocObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rating": %s,
           "success": %s,
           "explosiveness": %s,
           "rushing": %s,
           "pasing": %s,
           "standardDowns": %s,
           "passingDowns": %s,
           "havoc": %s
        }',
        self$`rating`,
        self$`success`,
        self$`explosiveness`,
        self$`rushing`,
        self$`pasing`,
        self$`standardDowns`,
        self$`passingDowns`,
        self$`havoc`$toJSON()
      )
    },
    fromJSONString = function(ConferenceSPRatingDefenseJson) {
      ConferenceSPRatingDefenseObject <- jsonlite::fromJSON(ConferenceSPRatingDefenseJson)
      self$`rating` <- ConferenceSPRatingDefenseObject$`rating`
      self$`success` <- ConferenceSPRatingDefenseObject$`success`
      self$`explosiveness` <- ConferenceSPRatingDefenseObject$`explosiveness`
      self$`rushing` <- ConferenceSPRatingDefenseObject$`rushing`
      self$`pasing` <- ConferenceSPRatingDefenseObject$`pasing`
      self$`standardDowns` <- ConferenceSPRatingDefenseObject$`standardDowns`
      self$`passingDowns` <- ConferenceSPRatingDefenseObject$`passingDowns`
      TeamSPRatingDefenseHavocObject <- TeamSPRatingDefenseHavoc$new()
      self$`havoc` <- TeamSPRatingDefenseHavocObject$fromJSON(jsonlite::toJSON(ConferenceSPRatingDefenseObject$havoc, auto_unbox = TRUE))
    }
  )
)
