# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GameMedia Class
#'
#' @field id 
#' @field season 
#' @field week 
#' @field seasonType 
#' @field startTime 
#' @field isStartTimeTBD 
#' @field homeTeam 
#' @field homeConference 
#' @field awayTeam 
#' @field awayConference 
#' @field mediaType 
#' @field outlet 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameMedia <- R6::R6Class(
  'GameMedia',
  public = list(
    `id` = NULL,
    `season` = NULL,
    `week` = NULL,
    `seasonType` = NULL,
    `startTime` = NULL,
    `isStartTimeTBD` = NULL,
    `homeTeam` = NULL,
    `homeConference` = NULL,
    `awayTeam` = NULL,
    `awayConference` = NULL,
    `mediaType` = NULL,
    `outlet` = NULL,
    initialize = function(`id`, `season`, `week`, `seasonType`, `startTime`, `isStartTimeTBD`, `homeTeam`, `homeConference`, `awayTeam`, `awayConference`, `mediaType`, `outlet`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`season`)) {
        stopifnot(is.numeric(`season`), length(`season`) == 1)
        self$`season` <- `season`
      }
      if (!missing(`week`)) {
        stopifnot(is.numeric(`week`), length(`week`) == 1)
        self$`week` <- `week`
      }
      if (!missing(`seasonType`)) {
        stopifnot(is.character(`seasonType`), length(`seasonType`) == 1)
        self$`seasonType` <- `seasonType`
      }
      if (!missing(`startTime`)) {
        stopifnot(is.character(`startTime`), length(`startTime`) == 1)
        self$`startTime` <- `startTime`
      }
      if (!missing(`isStartTimeTBD`)) {
        self$`isStartTimeTBD` <- `isStartTimeTBD`
      }
      if (!missing(`homeTeam`)) {
        stopifnot(is.character(`homeTeam`), length(`homeTeam`) == 1)
        self$`homeTeam` <- `homeTeam`
      }
      if (!missing(`homeConference`)) {
        stopifnot(is.character(`homeConference`), length(`homeConference`) == 1)
        self$`homeConference` <- `homeConference`
      }
      if (!missing(`awayTeam`)) {
        stopifnot(is.character(`awayTeam`), length(`awayTeam`) == 1)
        self$`awayTeam` <- `awayTeam`
      }
      if (!missing(`awayConference`)) {
        stopifnot(is.character(`awayConference`), length(`awayConference`) == 1)
        self$`awayConference` <- `awayConference`
      }
      if (!missing(`mediaType`)) {
        stopifnot(is.character(`mediaType`), length(`mediaType`) == 1)
        self$`mediaType` <- `mediaType`
      }
      if (!missing(`outlet`)) {
        stopifnot(is.character(`outlet`), length(`outlet`) == 1)
        self$`outlet` <- `outlet`
      }
    },
    toJSON = function() {
      GameMediaObject <- list()
      if (!is.null(self$`id`)) {
        GameMediaObject[['id']] <- self$`id`
      }
      if (!is.null(self$`season`)) {
        GameMediaObject[['season']] <- self$`season`
      }
      if (!is.null(self$`week`)) {
        GameMediaObject[['week']] <- self$`week`
      }
      if (!is.null(self$`seasonType`)) {
        GameMediaObject[['seasonType']] <- self$`seasonType`
      }
      if (!is.null(self$`startTime`)) {
        GameMediaObject[['startTime']] <- self$`startTime`
      }
      if (!is.null(self$`isStartTimeTBD`)) {
        GameMediaObject[['isStartTimeTBD']] <- self$`isStartTimeTBD`
      }
      if (!is.null(self$`homeTeam`)) {
        GameMediaObject[['homeTeam']] <- self$`homeTeam`
      }
      if (!is.null(self$`homeConference`)) {
        GameMediaObject[['homeConference']] <- self$`homeConference`
      }
      if (!is.null(self$`awayTeam`)) {
        GameMediaObject[['awayTeam']] <- self$`awayTeam`
      }
      if (!is.null(self$`awayConference`)) {
        GameMediaObject[['awayConference']] <- self$`awayConference`
      }
      if (!is.null(self$`mediaType`)) {
        GameMediaObject[['mediaType']] <- self$`mediaType`
      }
      if (!is.null(self$`outlet`)) {
        GameMediaObject[['outlet']] <- self$`outlet`
      }

      GameMediaObject
    },
    fromJSON = function(GameMediaJson) {
      GameMediaObject <- jsonlite::fromJSON(GameMediaJson)
      if (!is.null(GameMediaObject$`id`)) {
        self$`id` <- GameMediaObject$`id`
      }
      if (!is.null(GameMediaObject$`season`)) {
        self$`season` <- GameMediaObject$`season`
      }
      if (!is.null(GameMediaObject$`week`)) {
        self$`week` <- GameMediaObject$`week`
      }
      if (!is.null(GameMediaObject$`seasonType`)) {
        self$`seasonType` <- GameMediaObject$`seasonType`
      }
      if (!is.null(GameMediaObject$`startTime`)) {
        self$`startTime` <- GameMediaObject$`startTime`
      }
      if (!is.null(GameMediaObject$`isStartTimeTBD`)) {
        self$`isStartTimeTBD` <- GameMediaObject$`isStartTimeTBD`
      }
      if (!is.null(GameMediaObject$`homeTeam`)) {
        self$`homeTeam` <- GameMediaObject$`homeTeam`
      }
      if (!is.null(GameMediaObject$`homeConference`)) {
        self$`homeConference` <- GameMediaObject$`homeConference`
      }
      if (!is.null(GameMediaObject$`awayTeam`)) {
        self$`awayTeam` <- GameMediaObject$`awayTeam`
      }
      if (!is.null(GameMediaObject$`awayConference`)) {
        self$`awayConference` <- GameMediaObject$`awayConference`
      }
      if (!is.null(GameMediaObject$`mediaType`)) {
        self$`mediaType` <- GameMediaObject$`mediaType`
      }
      if (!is.null(GameMediaObject$`outlet`)) {
        self$`outlet` <- GameMediaObject$`outlet`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "season": %d,
           "week": %d,
           "seasonType": %s,
           "startTime": %s,
           "isStartTimeTBD": %s,
           "homeTeam": %s,
           "homeConference": %s,
           "awayTeam": %s,
           "awayConference": %s,
           "mediaType": %s,
           "outlet": %s
        }',
        self$`id`,
        self$`season`,
        self$`week`,
        self$`seasonType`,
        self$`startTime`,
        self$`isStartTimeTBD`,
        self$`homeTeam`,
        self$`homeConference`,
        self$`awayTeam`,
        self$`awayConference`,
        self$`mediaType`,
        self$`outlet`
      )
    },
    fromJSONString = function(GameMediaJson) {
      GameMediaObject <- jsonlite::fromJSON(GameMediaJson)
      self$`id` <- GameMediaObject$`id`
      self$`season` <- GameMediaObject$`season`
      self$`week` <- GameMediaObject$`week`
      self$`seasonType` <- GameMediaObject$`seasonType`
      self$`startTime` <- GameMediaObject$`startTime`
      self$`isStartTimeTBD` <- GameMediaObject$`isStartTimeTBD`
      self$`homeTeam` <- GameMediaObject$`homeTeam`
      self$`homeConference` <- GameMediaObject$`homeConference`
      self$`awayTeam` <- GameMediaObject$`awayTeam`
      self$`awayConference` <- GameMediaObject$`awayConference`
      self$`mediaType` <- GameMediaObject$`mediaType`
      self$`outlet` <- GameMediaObject$`outlet`
    }
  )
)
