# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GameLinesLines Class
#'
#' @field provider 
#' @field spread 
#' @field formattedSpread 
#' @field overUnder 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameLinesLines <- R6::R6Class(
  'GameLinesLines',
  public = list(
    `provider` = NULL,
    `spread` = NULL,
    `formattedSpread` = NULL,
    `overUnder` = NULL,
    initialize = function(`provider`, `spread`, `formattedSpread`, `overUnder`){
      if (!missing(`provider`)) {
        stopifnot(is.character(`provider`), length(`provider`) == 1)
        self$`provider` <- `provider`
      }
      if (!missing(`spread`)) {
        self$`spread` <- `spread`
      }
      if (!missing(`formattedSpread`)) {
        stopifnot(is.character(`formattedSpread`), length(`formattedSpread`) == 1)
        self$`formattedSpread` <- `formattedSpread`
      }
      if (!missing(`overUnder`)) {
        self$`overUnder` <- `overUnder`
      }
    },
    toJSON = function() {
      GameLinesLinesObject <- list()
      if (!is.null(self$`provider`)) {
        GameLinesLinesObject[['provider']] <- self$`provider`
      }
      if (!is.null(self$`spread`)) {
        GameLinesLinesObject[['spread']] <- self$`spread`
      }
      if (!is.null(self$`formattedSpread`)) {
        GameLinesLinesObject[['formattedSpread']] <- self$`formattedSpread`
      }
      if (!is.null(self$`overUnder`)) {
        GameLinesLinesObject[['overUnder']] <- self$`overUnder`
      }

      GameLinesLinesObject
    },
    fromJSON = function(GameLinesLinesJson) {
      GameLinesLinesObject <- jsonlite::fromJSON(GameLinesLinesJson)
      if (!is.null(GameLinesLinesObject$`provider`)) {
        self$`provider` <- GameLinesLinesObject$`provider`
      }
      if (!is.null(GameLinesLinesObject$`spread`)) {
        self$`spread` <- GameLinesLinesObject$`spread`
      }
      if (!is.null(GameLinesLinesObject$`formattedSpread`)) {
        self$`formattedSpread` <- GameLinesLinesObject$`formattedSpread`
      }
      if (!is.null(GameLinesLinesObject$`overUnder`)) {
        self$`overUnder` <- GameLinesLinesObject$`overUnder`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "provider": %s,
           "spread": %s,
           "formattedSpread": %s,
           "overUnder": %s
        }',
        self$`provider`,
        self$`spread`,
        self$`formattedSpread`,
        self$`overUnder`
      )
    },
    fromJSONString = function(GameLinesLinesJson) {
      GameLinesLinesObject <- jsonlite::fromJSON(GameLinesLinesJson)
      self$`provider` <- GameLinesLinesObject$`provider`
      self$`spread` <- GameLinesLinesObject$`spread`
      self$`formattedSpread` <- GameLinesLinesObject$`formattedSpread`
      self$`overUnder` <- GameLinesLinesObject$`overUnder`
    }
  )
)
