# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PlayerSeasonPPAAveragePPA Class
#'
#' @field all 
#' @field pass 
#' @field rush 
#' @field firstDown 
#' @field secondDown 
#' @field thirdDown 
#' @field standardDowns 
#' @field passingDowns 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerSeasonPPAAveragePPA <- R6::R6Class(
  'PlayerSeasonPPAAveragePPA',
  public = list(
    `all` = NULL,
    `pass` = NULL,
    `rush` = NULL,
    `firstDown` = NULL,
    `secondDown` = NULL,
    `thirdDown` = NULL,
    `standardDowns` = NULL,
    `passingDowns` = NULL,
    initialize = function(`all`, `pass`, `rush`, `firstDown`, `secondDown`, `thirdDown`, `standardDowns`, `passingDowns`){
      if (!missing(`all`)) {
        self$`all` <- `all`
      }
      if (!missing(`pass`)) {
        self$`pass` <- `pass`
      }
      if (!missing(`rush`)) {
        self$`rush` <- `rush`
      }
      if (!missing(`firstDown`)) {
        self$`firstDown` <- `firstDown`
      }
      if (!missing(`secondDown`)) {
        self$`secondDown` <- `secondDown`
      }
      if (!missing(`thirdDown`)) {
        self$`thirdDown` <- `thirdDown`
      }
      if (!missing(`standardDowns`)) {
        self$`standardDowns` <- `standardDowns`
      }
      if (!missing(`passingDowns`)) {
        self$`passingDowns` <- `passingDowns`
      }
    },
    toJSON = function() {
      PlayerSeasonPPAAveragePPAObject <- list()
      if (!is.null(self$`all`)) {
        PlayerSeasonPPAAveragePPAObject[['all']] <- self$`all`
      }
      if (!is.null(self$`pass`)) {
        PlayerSeasonPPAAveragePPAObject[['pass']] <- self$`pass`
      }
      if (!is.null(self$`rush`)) {
        PlayerSeasonPPAAveragePPAObject[['rush']] <- self$`rush`
      }
      if (!is.null(self$`firstDown`)) {
        PlayerSeasonPPAAveragePPAObject[['firstDown']] <- self$`firstDown`
      }
      if (!is.null(self$`secondDown`)) {
        PlayerSeasonPPAAveragePPAObject[['secondDown']] <- self$`secondDown`
      }
      if (!is.null(self$`thirdDown`)) {
        PlayerSeasonPPAAveragePPAObject[['thirdDown']] <- self$`thirdDown`
      }
      if (!is.null(self$`standardDowns`)) {
        PlayerSeasonPPAAveragePPAObject[['standardDowns']] <- self$`standardDowns`
      }
      if (!is.null(self$`passingDowns`)) {
        PlayerSeasonPPAAveragePPAObject[['passingDowns']] <- self$`passingDowns`
      }

      PlayerSeasonPPAAveragePPAObject
    },
    fromJSON = function(PlayerSeasonPPAAveragePPAJson) {
      PlayerSeasonPPAAveragePPAObject <- jsonlite::fromJSON(PlayerSeasonPPAAveragePPAJson)
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`all`)) {
        self$`all` <- PlayerSeasonPPAAveragePPAObject$`all`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`pass`)) {
        self$`pass` <- PlayerSeasonPPAAveragePPAObject$`pass`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`rush`)) {
        self$`rush` <- PlayerSeasonPPAAveragePPAObject$`rush`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`firstDown`)) {
        self$`firstDown` <- PlayerSeasonPPAAveragePPAObject$`firstDown`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`secondDown`)) {
        self$`secondDown` <- PlayerSeasonPPAAveragePPAObject$`secondDown`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`thirdDown`)) {
        self$`thirdDown` <- PlayerSeasonPPAAveragePPAObject$`thirdDown`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`standardDowns`)) {
        self$`standardDowns` <- PlayerSeasonPPAAveragePPAObject$`standardDowns`
      }
      if (!is.null(PlayerSeasonPPAAveragePPAObject$`passingDowns`)) {
        self$`passingDowns` <- PlayerSeasonPPAAveragePPAObject$`passingDowns`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "all": %s,
           "pass": %s,
           "rush": %s,
           "firstDown": %s,
           "secondDown": %s,
           "thirdDown": %s,
           "standardDowns": %s,
           "passingDowns": %s
        }',
        self$`all`,
        self$`pass`,
        self$`rush`,
        self$`firstDown`,
        self$`secondDown`,
        self$`thirdDown`,
        self$`standardDowns`,
        self$`passingDowns`
      )
    },
    fromJSONString = function(PlayerSeasonPPAAveragePPAJson) {
      PlayerSeasonPPAAveragePPAObject <- jsonlite::fromJSON(PlayerSeasonPPAAveragePPAJson)
      self$`all` <- PlayerSeasonPPAAveragePPAObject$`all`
      self$`pass` <- PlayerSeasonPPAAveragePPAObject$`pass`
      self$`rush` <- PlayerSeasonPPAAveragePPAObject$`rush`
      self$`firstDown` <- PlayerSeasonPPAAveragePPAObject$`firstDown`
      self$`secondDown` <- PlayerSeasonPPAAveragePPAObject$`secondDown`
      self$`thirdDown` <- PlayerSeasonPPAAveragePPAObject$`thirdDown`
      self$`standardDowns` <- PlayerSeasonPPAAveragePPAObject$`standardDowns`
      self$`passingDowns` <- PlayerSeasonPPAAveragePPAObject$`passingDowns`
    }
  )
)
