# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PlayerUsageUsage Class
#'
#' @field overall 
#' @field pass 
#' @field rush 
#' @field firstDown 
#' @field secondDown 
#' @field thirdDown 
#' @field standardDowns 
#' @field passingDowns 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerUsageUsage <- R6::R6Class(
  'PlayerUsageUsage',
  public = list(
    `overall` = NULL,
    `pass` = NULL,
    `rush` = NULL,
    `firstDown` = NULL,
    `secondDown` = NULL,
    `thirdDown` = NULL,
    `standardDowns` = NULL,
    `passingDowns` = NULL,
    initialize = function(`overall`, `pass`, `rush`, `firstDown`, `secondDown`, `thirdDown`, `standardDowns`, `passingDowns`){
      if (!missing(`overall`)) {
        self$`overall` <- `overall`
      }
      if (!missing(`pass`)) {
        self$`pass` <- `pass`
      }
      if (!missing(`rush`)) {
        self$`rush` <- `rush`
      }
      if (!missing(`firstDown`)) {
        self$`firstDown` <- `firstDown`
      }
      if (!missing(`secondDown`)) {
        self$`secondDown` <- `secondDown`
      }
      if (!missing(`thirdDown`)) {
        self$`thirdDown` <- `thirdDown`
      }
      if (!missing(`standardDowns`)) {
        self$`standardDowns` <- `standardDowns`
      }
      if (!missing(`passingDowns`)) {
        self$`passingDowns` <- `passingDowns`
      }
    },
    toJSON = function() {
      PlayerUsageUsageObject <- list()
      if (!is.null(self$`overall`)) {
        PlayerUsageUsageObject[['overall']] <- self$`overall`
      }
      if (!is.null(self$`pass`)) {
        PlayerUsageUsageObject[['pass']] <- self$`pass`
      }
      if (!is.null(self$`rush`)) {
        PlayerUsageUsageObject[['rush']] <- self$`rush`
      }
      if (!is.null(self$`firstDown`)) {
        PlayerUsageUsageObject[['firstDown']] <- self$`firstDown`
      }
      if (!is.null(self$`secondDown`)) {
        PlayerUsageUsageObject[['secondDown']] <- self$`secondDown`
      }
      if (!is.null(self$`thirdDown`)) {
        PlayerUsageUsageObject[['thirdDown']] <- self$`thirdDown`
      }
      if (!is.null(self$`standardDowns`)) {
        PlayerUsageUsageObject[['standardDowns']] <- self$`standardDowns`
      }
      if (!is.null(self$`passingDowns`)) {
        PlayerUsageUsageObject[['passingDowns']] <- self$`passingDowns`
      }

      PlayerUsageUsageObject
    },
    fromJSON = function(PlayerUsageUsageJson) {
      PlayerUsageUsageObject <- jsonlite::fromJSON(PlayerUsageUsageJson)
      if (!is.null(PlayerUsageUsageObject$`overall`)) {
        self$`overall` <- PlayerUsageUsageObject$`overall`
      }
      if (!is.null(PlayerUsageUsageObject$`pass`)) {
        self$`pass` <- PlayerUsageUsageObject$`pass`
      }
      if (!is.null(PlayerUsageUsageObject$`rush`)) {
        self$`rush` <- PlayerUsageUsageObject$`rush`
      }
      if (!is.null(PlayerUsageUsageObject$`firstDown`)) {
        self$`firstDown` <- PlayerUsageUsageObject$`firstDown`
      }
      if (!is.null(PlayerUsageUsageObject$`secondDown`)) {
        self$`secondDown` <- PlayerUsageUsageObject$`secondDown`
      }
      if (!is.null(PlayerUsageUsageObject$`thirdDown`)) {
        self$`thirdDown` <- PlayerUsageUsageObject$`thirdDown`
      }
      if (!is.null(PlayerUsageUsageObject$`standardDowns`)) {
        self$`standardDowns` <- PlayerUsageUsageObject$`standardDowns`
      }
      if (!is.null(PlayerUsageUsageObject$`passingDowns`)) {
        self$`passingDowns` <- PlayerUsageUsageObject$`passingDowns`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "overall": %s,
           "pass": %s,
           "rush": %s,
           "firstDown": %s,
           "secondDown": %s,
           "thirdDown": %s,
           "standardDowns": %s,
           "passingDowns": %s
        }',
        self$`overall`,
        self$`pass`,
        self$`rush`,
        self$`firstDown`,
        self$`secondDown`,
        self$`thirdDown`,
        self$`standardDowns`,
        self$`passingDowns`
      )
    },
    fromJSONString = function(PlayerUsageUsageJson) {
      PlayerUsageUsageObject <- jsonlite::fromJSON(PlayerUsageUsageJson)
      self$`overall` <- PlayerUsageUsageObject$`overall`
      self$`pass` <- PlayerUsageUsageObject$`pass`
      self$`rush` <- PlayerUsageUsageObject$`rush`
      self$`firstDown` <- PlayerUsageUsageObject$`firstDown`
      self$`secondDown` <- PlayerUsageUsageObject$`secondDown`
      self$`thirdDown` <- PlayerUsageUsageObject$`thirdDown`
      self$`standardDowns` <- PlayerUsageUsageObject$`standardDowns`
      self$`passingDowns` <- PlayerUsageUsageObject$`passingDowns`
    }
  )
)
