# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PlayerGameAthletes Class
#'
#' @field id 
#' @field name 
#' @field stat 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerGameAthletes <- R6::R6Class(
  'PlayerGameAthletes',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `stat` = NULL,
    initialize = function(`id`, `name`, `stat`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`stat`)) {
        stopifnot(is.character(`stat`), length(`stat`) == 1)
        self$`stat` <- `stat`
      }
    },
    toJSON = function() {
      PlayerGameAthletesObject <- list()
      if (!is.null(self$`id`)) {
        PlayerGameAthletesObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        PlayerGameAthletesObject[['name']] <- self$`name`
      }
      if (!is.null(self$`stat`)) {
        PlayerGameAthletesObject[['stat']] <- self$`stat`
      }

      PlayerGameAthletesObject
    },
    fromJSON = function(PlayerGameAthletesJson) {
      PlayerGameAthletesObject <- jsonlite::fromJSON(PlayerGameAthletesJson)
      if (!is.null(PlayerGameAthletesObject$`id`)) {
        self$`id` <- PlayerGameAthletesObject$`id`
      }
      if (!is.null(PlayerGameAthletesObject$`name`)) {
        self$`name` <- PlayerGameAthletesObject$`name`
      }
      if (!is.null(PlayerGameAthletesObject$`stat`)) {
        self$`stat` <- PlayerGameAthletesObject$`stat`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "name": %s,
           "stat": %s
        }',
        self$`id`,
        self$`name`,
        self$`stat`
      )
    },
    fromJSONString = function(PlayerGameAthletesJson) {
      PlayerGameAthletesObject <- jsonlite::fromJSON(PlayerGameAthletesJson)
      self$`id` <- PlayerGameAthletesObject$`id`
      self$`name` <- PlayerGameAthletesObject$`name`
      self$`stat` <- PlayerGameAthletesObject$`stat`
    }
  )
)
