# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PlayerGamePPAAveragePPA Class
#'
#' @field all 
#' @field pass 
#' @field rush 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerGamePPAAveragePPA <- R6::R6Class(
  'PlayerGamePPAAveragePPA',
  public = list(
    `all` = NULL,
    `pass` = NULL,
    `rush` = NULL,
    initialize = function(`all`, `pass`, `rush`){
      if (!missing(`all`)) {
        self$`all` <- `all`
      }
      if (!missing(`pass`)) {
        self$`pass` <- `pass`
      }
      if (!missing(`rush`)) {
        self$`rush` <- `rush`
      }
    },
    toJSON = function() {
      PlayerGamePPAAveragePPAObject <- list()
      if (!is.null(self$`all`)) {
        PlayerGamePPAAveragePPAObject[['all']] <- self$`all`
      }
      if (!is.null(self$`pass`)) {
        PlayerGamePPAAveragePPAObject[['pass']] <- self$`pass`
      }
      if (!is.null(self$`rush`)) {
        PlayerGamePPAAveragePPAObject[['rush']] <- self$`rush`
      }

      PlayerGamePPAAveragePPAObject
    },
    fromJSON = function(PlayerGamePPAAveragePPAJson) {
      PlayerGamePPAAveragePPAObject <- jsonlite::fromJSON(PlayerGamePPAAveragePPAJson)
      if (!is.null(PlayerGamePPAAveragePPAObject$`all`)) {
        self$`all` <- PlayerGamePPAAveragePPAObject$`all`
      }
      if (!is.null(PlayerGamePPAAveragePPAObject$`pass`)) {
        self$`pass` <- PlayerGamePPAAveragePPAObject$`pass`
      }
      if (!is.null(PlayerGamePPAAveragePPAObject$`rush`)) {
        self$`rush` <- PlayerGamePPAAveragePPAObject$`rush`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "all": %s,
           "pass": %s,
           "rush": %s
        }',
        self$`all`,
        self$`pass`,
        self$`rush`
      )
    },
    fromJSONString = function(PlayerGamePPAAveragePPAJson) {
      PlayerGamePPAAveragePPAObject <- jsonlite::fromJSON(PlayerGamePPAAveragePPAJson)
      self$`all` <- PlayerGamePPAAveragePPAObject$`all`
      self$`pass` <- PlayerGamePPAAveragePPAObject$`pass`
      self$`rush` <- PlayerGamePPAAveragePPAObject$`rush`
    }
  )
)
