# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PositionGroupRecruitingRating Class
#'
#' @field team 
#' @field conference 
#' @field positiionGroup 
#' @field averageRating 
#' @field totalRating 
#' @field commits 
#' @field averageStars 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PositionGroupRecruitingRating <- R6::R6Class(
  'PositionGroupRecruitingRating',
  public = list(
    `team` = NULL,
    `conference` = NULL,
    `positiionGroup` = NULL,
    `averageRating` = NULL,
    `totalRating` = NULL,
    `commits` = NULL,
    `averageStars` = NULL,
    initialize = function(`team`, `conference`, `positiionGroup`, `averageRating`, `totalRating`, `commits`, `averageStars`){
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`conference`)) {
        stopifnot(is.character(`conference`), length(`conference`) == 1)
        self$`conference` <- `conference`
      }
      if (!missing(`positiionGroup`)) {
        stopifnot(is.character(`positiionGroup`), length(`positiionGroup`) == 1)
        self$`positiionGroup` <- `positiionGroup`
      }
      if (!missing(`averageRating`)) {
        self$`averageRating` <- `averageRating`
      }
      if (!missing(`totalRating`)) {
        self$`totalRating` <- `totalRating`
      }
      if (!missing(`commits`)) {
        self$`commits` <- `commits`
      }
      if (!missing(`averageStars`)) {
        self$`averageStars` <- `averageStars`
      }
    },
    toJSON = function() {
      PositionGroupRecruitingRatingObject <- list()
      if (!is.null(self$`team`)) {
        PositionGroupRecruitingRatingObject[['team']] <- self$`team`
      }
      if (!is.null(self$`conference`)) {
        PositionGroupRecruitingRatingObject[['conference']] <- self$`conference`
      }
      if (!is.null(self$`positiionGroup`)) {
        PositionGroupRecruitingRatingObject[['positiionGroup']] <- self$`positiionGroup`
      }
      if (!is.null(self$`averageRating`)) {
        PositionGroupRecruitingRatingObject[['averageRating']] <- self$`averageRating`
      }
      if (!is.null(self$`totalRating`)) {
        PositionGroupRecruitingRatingObject[['totalRating']] <- self$`totalRating`
      }
      if (!is.null(self$`commits`)) {
        PositionGroupRecruitingRatingObject[['commits']] <- self$`commits`
      }
      if (!is.null(self$`averageStars`)) {
        PositionGroupRecruitingRatingObject[['averageStars']] <- self$`averageStars`
      }

      PositionGroupRecruitingRatingObject
    },
    fromJSON = function(PositionGroupRecruitingRatingJson) {
      PositionGroupRecruitingRatingObject <- jsonlite::fromJSON(PositionGroupRecruitingRatingJson)
      if (!is.null(PositionGroupRecruitingRatingObject$`team`)) {
        self$`team` <- PositionGroupRecruitingRatingObject$`team`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`conference`)) {
        self$`conference` <- PositionGroupRecruitingRatingObject$`conference`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`positiionGroup`)) {
        self$`positiionGroup` <- PositionGroupRecruitingRatingObject$`positiionGroup`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`averageRating`)) {
        self$`averageRating` <- PositionGroupRecruitingRatingObject$`averageRating`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`totalRating`)) {
        self$`totalRating` <- PositionGroupRecruitingRatingObject$`totalRating`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`commits`)) {
        self$`commits` <- PositionGroupRecruitingRatingObject$`commits`
      }
      if (!is.null(PositionGroupRecruitingRatingObject$`averageStars`)) {
        self$`averageStars` <- PositionGroupRecruitingRatingObject$`averageStars`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "team": %s,
           "conference": %s,
           "positiionGroup": %s,
           "averageRating": %s,
           "totalRating": %s,
           "commits": %s,
           "averageStars": %s
        }',
        self$`team`,
        self$`conference`,
        self$`positiionGroup`,
        self$`averageRating`,
        self$`totalRating`,
        self$`commits`,
        self$`averageStars`
      )
    },
    fromJSONString = function(PositionGroupRecruitingRatingJson) {
      PositionGroupRecruitingRatingObject <- jsonlite::fromJSON(PositionGroupRecruitingRatingJson)
      self$`team` <- PositionGroupRecruitingRatingObject$`team`
      self$`conference` <- PositionGroupRecruitingRatingObject$`conference`
      self$`positiionGroup` <- PositionGroupRecruitingRatingObject$`positiionGroup`
      self$`averageRating` <- PositionGroupRecruitingRatingObject$`averageRating`
      self$`totalRating` <- PositionGroupRecruitingRatingObject$`totalRating`
      self$`commits` <- PositionGroupRecruitingRatingObject$`commits`
      self$`averageStars` <- PositionGroupRecruitingRatingObject$`averageStars`
    }
  )
)
