# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamSPRatingOffense Class
#'
#' @field ranking 
#' @field rating 
#' @field success 
#' @field explosiveness 
#' @field rushing 
#' @field passing 
#' @field standardDowns 
#' @field passingDowns 
#' @field runRate 
#' @field pace 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamSPRatingOffense <- R6::R6Class(
  'TeamSPRatingOffense',
  public = list(
    `ranking` = NULL,
    `rating` = NULL,
    `success` = NULL,
    `explosiveness` = NULL,
    `rushing` = NULL,
    `passing` = NULL,
    `standardDowns` = NULL,
    `passingDowns` = NULL,
    `runRate` = NULL,
    `pace` = NULL,
    initialize = function(`ranking`, `rating`, `success`, `explosiveness`, `rushing`, `passing`, `standardDowns`, `passingDowns`, `runRate`, `pace`){
      if (!missing(`ranking`)) {
        self$`ranking` <- `ranking`
      }
      if (!missing(`rating`)) {
        self$`rating` <- `rating`
      }
      if (!missing(`success`)) {
        self$`success` <- `success`
      }
      if (!missing(`explosiveness`)) {
        self$`explosiveness` <- `explosiveness`
      }
      if (!missing(`rushing`)) {
        self$`rushing` <- `rushing`
      }
      if (!missing(`passing`)) {
        self$`passing` <- `passing`
      }
      if (!missing(`standardDowns`)) {
        self$`standardDowns` <- `standardDowns`
      }
      if (!missing(`passingDowns`)) {
        self$`passingDowns` <- `passingDowns`
      }
      if (!missing(`runRate`)) {
        self$`runRate` <- `runRate`
      }
      if (!missing(`pace`)) {
        self$`pace` <- `pace`
      }
    },
    toJSON = function() {
      TeamSPRatingOffenseObject <- list()
      if (!is.null(self$`ranking`)) {
        TeamSPRatingOffenseObject[['ranking']] <- self$`ranking`
      }
      if (!is.null(self$`rating`)) {
        TeamSPRatingOffenseObject[['rating']] <- self$`rating`
      }
      if (!is.null(self$`success`)) {
        TeamSPRatingOffenseObject[['success']] <- self$`success`
      }
      if (!is.null(self$`explosiveness`)) {
        TeamSPRatingOffenseObject[['explosiveness']] <- self$`explosiveness`
      }
      if (!is.null(self$`rushing`)) {
        TeamSPRatingOffenseObject[['rushing']] <- self$`rushing`
      }
      if (!is.null(self$`passing`)) {
        TeamSPRatingOffenseObject[['passing']] <- self$`passing`
      }
      if (!is.null(self$`standardDowns`)) {
        TeamSPRatingOffenseObject[['standardDowns']] <- self$`standardDowns`
      }
      if (!is.null(self$`passingDowns`)) {
        TeamSPRatingOffenseObject[['passingDowns']] <- self$`passingDowns`
      }
      if (!is.null(self$`runRate`)) {
        TeamSPRatingOffenseObject[['runRate']] <- self$`runRate`
      }
      if (!is.null(self$`pace`)) {
        TeamSPRatingOffenseObject[['pace']] <- self$`pace`
      }

      TeamSPRatingOffenseObject
    },
    fromJSON = function(TeamSPRatingOffenseJson) {
      TeamSPRatingOffenseObject <- jsonlite::fromJSON(TeamSPRatingOffenseJson)
      if (!is.null(TeamSPRatingOffenseObject$`ranking`)) {
        self$`ranking` <- TeamSPRatingOffenseObject$`ranking`
      }
      if (!is.null(TeamSPRatingOffenseObject$`rating`)) {
        self$`rating` <- TeamSPRatingOffenseObject$`rating`
      }
      if (!is.null(TeamSPRatingOffenseObject$`success`)) {
        self$`success` <- TeamSPRatingOffenseObject$`success`
      }
      if (!is.null(TeamSPRatingOffenseObject$`explosiveness`)) {
        self$`explosiveness` <- TeamSPRatingOffenseObject$`explosiveness`
      }
      if (!is.null(TeamSPRatingOffenseObject$`rushing`)) {
        self$`rushing` <- TeamSPRatingOffenseObject$`rushing`
      }
      if (!is.null(TeamSPRatingOffenseObject$`passing`)) {
        self$`passing` <- TeamSPRatingOffenseObject$`passing`
      }
      if (!is.null(TeamSPRatingOffenseObject$`standardDowns`)) {
        self$`standardDowns` <- TeamSPRatingOffenseObject$`standardDowns`
      }
      if (!is.null(TeamSPRatingOffenseObject$`passingDowns`)) {
        self$`passingDowns` <- TeamSPRatingOffenseObject$`passingDowns`
      }
      if (!is.null(TeamSPRatingOffenseObject$`runRate`)) {
        self$`runRate` <- TeamSPRatingOffenseObject$`runRate`
      }
      if (!is.null(TeamSPRatingOffenseObject$`pace`)) {
        self$`pace` <- TeamSPRatingOffenseObject$`pace`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ranking": %s,
           "rating": %s,
           "success": %s,
           "explosiveness": %s,
           "rushing": %s,
           "passing": %s,
           "standardDowns": %s,
           "passingDowns": %s,
           "runRate": %s,
           "pace": %s
        }',
        self$`ranking`,
        self$`rating`,
        self$`success`,
        self$`explosiveness`,
        self$`rushing`,
        self$`passing`,
        self$`standardDowns`,
        self$`passingDowns`,
        self$`runRate`,
        self$`pace`
      )
    },
    fromJSONString = function(TeamSPRatingOffenseJson) {
      TeamSPRatingOffenseObject <- jsonlite::fromJSON(TeamSPRatingOffenseJson)
      self$`ranking` <- TeamSPRatingOffenseObject$`ranking`
      self$`rating` <- TeamSPRatingOffenseObject$`rating`
      self$`success` <- TeamSPRatingOffenseObject$`success`
      self$`explosiveness` <- TeamSPRatingOffenseObject$`explosiveness`
      self$`rushing` <- TeamSPRatingOffenseObject$`rushing`
      self$`passing` <- TeamSPRatingOffenseObject$`passing`
      self$`standardDowns` <- TeamSPRatingOffenseObject$`standardDowns`
      self$`passingDowns` <- TeamSPRatingOffenseObject$`passingDowns`
      self$`runRate` <- TeamSPRatingOffenseObject$`runRate`
      self$`pace` <- TeamSPRatingOffenseObject$`pace`
    }
  )
)
