# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamSPRatingDefense Class
#'
#' @field ranking 
#' @field rating 
#' @field success 
#' @field explosiveness 
#' @field rushing 
#' @field pasing 
#' @field standardDowns 
#' @field passingDowns 
#' @field havoc 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamSPRatingDefense <- R6::R6Class(
  'TeamSPRatingDefense',
  public = list(
    `ranking` = NULL,
    `rating` = NULL,
    `success` = NULL,
    `explosiveness` = NULL,
    `rushing` = NULL,
    `pasing` = NULL,
    `standardDowns` = NULL,
    `passingDowns` = NULL,
    `havoc` = NULL,
    initialize = function(`ranking`, `rating`, `success`, `explosiveness`, `rushing`, `pasing`, `standardDowns`, `passingDowns`, `havoc`){
      if (!missing(`ranking`)) {
        self$`ranking` <- `ranking`
      }
      if (!missing(`rating`)) {
        self$`rating` <- `rating`
      }
      if (!missing(`success`)) {
        self$`success` <- `success`
      }
      if (!missing(`explosiveness`)) {
        self$`explosiveness` <- `explosiveness`
      }
      if (!missing(`rushing`)) {
        self$`rushing` <- `rushing`
      }
      if (!missing(`pasing`)) {
        self$`pasing` <- `pasing`
      }
      if (!missing(`standardDowns`)) {
        self$`standardDowns` <- `standardDowns`
      }
      if (!missing(`passingDowns`)) {
        self$`passingDowns` <- `passingDowns`
      }
      if (!missing(`havoc`)) {
        stopifnot(R6::is.R6(`havoc`))
        self$`havoc` <- `havoc`
      }
    },
    toJSON = function() {
      TeamSPRatingDefenseObject <- list()
      if (!is.null(self$`ranking`)) {
        TeamSPRatingDefenseObject[['ranking']] <- self$`ranking`
      }
      if (!is.null(self$`rating`)) {
        TeamSPRatingDefenseObject[['rating']] <- self$`rating`
      }
      if (!is.null(self$`success`)) {
        TeamSPRatingDefenseObject[['success']] <- self$`success`
      }
      if (!is.null(self$`explosiveness`)) {
        TeamSPRatingDefenseObject[['explosiveness']] <- self$`explosiveness`
      }
      if (!is.null(self$`rushing`)) {
        TeamSPRatingDefenseObject[['rushing']] <- self$`rushing`
      }
      if (!is.null(self$`pasing`)) {
        TeamSPRatingDefenseObject[['pasing']] <- self$`pasing`
      }
      if (!is.null(self$`standardDowns`)) {
        TeamSPRatingDefenseObject[['standardDowns']] <- self$`standardDowns`
      }
      if (!is.null(self$`passingDowns`)) {
        TeamSPRatingDefenseObject[['passingDowns']] <- self$`passingDowns`
      }
      if (!is.null(self$`havoc`)) {
        TeamSPRatingDefenseObject[['havoc']] <- self$`havoc`$toJSON()
      }

      TeamSPRatingDefenseObject
    },
    fromJSON = function(TeamSPRatingDefenseJson) {
      TeamSPRatingDefenseObject <- jsonlite::fromJSON(TeamSPRatingDefenseJson)
      if (!is.null(TeamSPRatingDefenseObject$`ranking`)) {
        self$`ranking` <- TeamSPRatingDefenseObject$`ranking`
      }
      if (!is.null(TeamSPRatingDefenseObject$`rating`)) {
        self$`rating` <- TeamSPRatingDefenseObject$`rating`
      }
      if (!is.null(TeamSPRatingDefenseObject$`success`)) {
        self$`success` <- TeamSPRatingDefenseObject$`success`
      }
      if (!is.null(TeamSPRatingDefenseObject$`explosiveness`)) {
        self$`explosiveness` <- TeamSPRatingDefenseObject$`explosiveness`
      }
      if (!is.null(TeamSPRatingDefenseObject$`rushing`)) {
        self$`rushing` <- TeamSPRatingDefenseObject$`rushing`
      }
      if (!is.null(TeamSPRatingDefenseObject$`pasing`)) {
        self$`pasing` <- TeamSPRatingDefenseObject$`pasing`
      }
      if (!is.null(TeamSPRatingDefenseObject$`standardDowns`)) {
        self$`standardDowns` <- TeamSPRatingDefenseObject$`standardDowns`
      }
      if (!is.null(TeamSPRatingDefenseObject$`passingDowns`)) {
        self$`passingDowns` <- TeamSPRatingDefenseObject$`passingDowns`
      }
      if (!is.null(TeamSPRatingDefenseObject$`havoc`)) {
        havocObject <- TeamSPRatingDefenseHavoc$new()
        havocObject$fromJSON(jsonlite::toJSON(TeamSPRatingDefenseObject$havoc, auto_unbox = TRUE))
        self$`havoc` <- havocObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ranking": %s,
           "rating": %s,
           "success": %s,
           "explosiveness": %s,
           "rushing": %s,
           "pasing": %s,
           "standardDowns": %s,
           "passingDowns": %s,
           "havoc": %s
        }',
        self$`ranking`,
        self$`rating`,
        self$`success`,
        self$`explosiveness`,
        self$`rushing`,
        self$`pasing`,
        self$`standardDowns`,
        self$`passingDowns`,
        self$`havoc`$toJSON()
      )
    },
    fromJSONString = function(TeamSPRatingDefenseJson) {
      TeamSPRatingDefenseObject <- jsonlite::fromJSON(TeamSPRatingDefenseJson)
      self$`ranking` <- TeamSPRatingDefenseObject$`ranking`
      self$`rating` <- TeamSPRatingDefenseObject$`rating`
      self$`success` <- TeamSPRatingDefenseObject$`success`
      self$`explosiveness` <- TeamSPRatingDefenseObject$`explosiveness`
      self$`rushing` <- TeamSPRatingDefenseObject$`rushing`
      self$`pasing` <- TeamSPRatingDefenseObject$`pasing`
      self$`standardDowns` <- TeamSPRatingDefenseObject$`standardDowns`
      self$`passingDowns` <- TeamSPRatingDefenseObject$`passingDowns`
      TeamSPRatingDefenseHavocObject <- TeamSPRatingDefenseHavoc$new()
      self$`havoc` <- TeamSPRatingDefenseHavocObject$fromJSON(jsonlite::toJSON(TeamSPRatingDefenseObject$havoc, auto_unbox = TRUE))
    }
  )
)
