# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamRecruitingRank Class
#'
#' @field year 
#' @field rank 
#' @field team 
#' @field points 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamRecruitingRank <- R6::R6Class(
  'TeamRecruitingRank',
  public = list(
    `year` = NULL,
    `rank` = NULL,
    `team` = NULL,
    `points` = NULL,
    initialize = function(`year`, `rank`, `team`, `points`){
      if (!missing(`year`)) {
        stopifnot(is.numeric(`year`), length(`year`) == 1)
        self$`year` <- `year`
      }
      if (!missing(`rank`)) {
        stopifnot(is.numeric(`rank`), length(`rank`) == 1)
        self$`rank` <- `rank`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`points`)) {
        self$`points` <- `points`
      }
    },
    toJSON = function() {
      TeamRecruitingRankObject <- list()
      if (!is.null(self$`year`)) {
        TeamRecruitingRankObject[['year']] <- self$`year`
      }
      if (!is.null(self$`rank`)) {
        TeamRecruitingRankObject[['rank']] <- self$`rank`
      }
      if (!is.null(self$`team`)) {
        TeamRecruitingRankObject[['team']] <- self$`team`
      }
      if (!is.null(self$`points`)) {
        TeamRecruitingRankObject[['points']] <- self$`points`
      }

      TeamRecruitingRankObject
    },
    fromJSON = function(TeamRecruitingRankJson) {
      TeamRecruitingRankObject <- jsonlite::fromJSON(TeamRecruitingRankJson)
      if (!is.null(TeamRecruitingRankObject$`year`)) {
        self$`year` <- TeamRecruitingRankObject$`year`
      }
      if (!is.null(TeamRecruitingRankObject$`rank`)) {
        self$`rank` <- TeamRecruitingRankObject$`rank`
      }
      if (!is.null(TeamRecruitingRankObject$`team`)) {
        self$`team` <- TeamRecruitingRankObject$`team`
      }
      if (!is.null(TeamRecruitingRankObject$`points`)) {
        self$`points` <- TeamRecruitingRankObject$`points`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "year": %d,
           "rank": %d,
           "team": %s,
           "points": %s
        }',
        self$`year`,
        self$`rank`,
        self$`team`,
        self$`points`
      )
    },
    fromJSONString = function(TeamRecruitingRankJson) {
      TeamRecruitingRankObject <- jsonlite::fromJSON(TeamRecruitingRankJson)
      self$`year` <- TeamRecruitingRankObject$`year`
      self$`rank` <- TeamRecruitingRankObject$`rank`
      self$`team` <- TeamRecruitingRankObject$`team`
      self$`points` <- TeamRecruitingRankObject$`points`
    }
  )
)
