# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamSeasonStat Class
#'
#' @field season 
#' @field team 
#' @field conference 
#' @field statName 
#' @field statValue 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamSeasonStat <- R6::R6Class(
  'TeamSeasonStat',
  public = list(
    `season` = NULL,
    `team` = NULL,
    `conference` = NULL,
    `statName` = NULL,
    `statValue` = NULL,
    initialize = function(`season`, `team`, `conference`, `statName`, `statValue`){
      if (!missing(`season`)) {
        stopifnot(is.numeric(`season`), length(`season`) == 1)
        self$`season` <- `season`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`conference`)) {
        stopifnot(is.character(`conference`), length(`conference`) == 1)
        self$`conference` <- `conference`
      }
      if (!missing(`statName`)) {
        stopifnot(is.character(`statName`), length(`statName`) == 1)
        self$`statName` <- `statName`
      }
      if (!missing(`statValue`)) {
        stopifnot(is.numeric(`statValue`), length(`statValue`) == 1)
        self$`statValue` <- `statValue`
      }
    },
    toJSON = function() {
      TeamSeasonStatObject <- list()
      if (!is.null(self$`season`)) {
        TeamSeasonStatObject[['season']] <- self$`season`
      }
      if (!is.null(self$`team`)) {
        TeamSeasonStatObject[['team']] <- self$`team`
      }
      if (!is.null(self$`conference`)) {
        TeamSeasonStatObject[['conference']] <- self$`conference`
      }
      if (!is.null(self$`statName`)) {
        TeamSeasonStatObject[['statName']] <- self$`statName`
      }
      if (!is.null(self$`statValue`)) {
        TeamSeasonStatObject[['statValue']] <- self$`statValue`
      }

      TeamSeasonStatObject
    },
    fromJSON = function(TeamSeasonStatJson) {
      TeamSeasonStatObject <- jsonlite::fromJSON(TeamSeasonStatJson)
      if (!is.null(TeamSeasonStatObject$`season`)) {
        self$`season` <- TeamSeasonStatObject$`season`
      }
      if (!is.null(TeamSeasonStatObject$`team`)) {
        self$`team` <- TeamSeasonStatObject$`team`
      }
      if (!is.null(TeamSeasonStatObject$`conference`)) {
        self$`conference` <- TeamSeasonStatObject$`conference`
      }
      if (!is.null(TeamSeasonStatObject$`statName`)) {
        self$`statName` <- TeamSeasonStatObject$`statName`
      }
      if (!is.null(TeamSeasonStatObject$`statValue`)) {
        self$`statValue` <- TeamSeasonStatObject$`statValue`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "season": %d,
           "team": %s,
           "conference": %s,
           "statName": %s,
           "statValue": %d
        }',
        self$`season`,
        self$`team`,
        self$`conference`,
        self$`statName`,
        self$`statValue`
      )
    },
    fromJSONString = function(TeamSeasonStatJson) {
      TeamSeasonStatObject <- jsonlite::fromJSON(TeamSeasonStatJson)
      self$`season` <- TeamSeasonStatObject$`season`
      self$`team` <- TeamSeasonStatObject$`team`
      self$`conference` <- TeamSeasonStatObject$`conference`
      self$`statName` <- TeamSeasonStatObject$`statName`
      self$`statValue` <- TeamSeasonStatObject$`statValue`
    }
  )
)
