# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamSPRatingSpecialTeams Class
#'
#' @field rating 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamSPRatingSpecialTeams <- R6::R6Class(
  'TeamSPRatingSpecialTeams',
  public = list(
    `rating` = NULL,
    initialize = function(`rating`){
      if (!missing(`rating`)) {
        self$`rating` <- `rating`
      }
    },
    toJSON = function() {
      TeamSPRatingSpecialTeamsObject <- list()
      if (!is.null(self$`rating`)) {
        TeamSPRatingSpecialTeamsObject[['rating']] <- self$`rating`
      }

      TeamSPRatingSpecialTeamsObject
    },
    fromJSON = function(TeamSPRatingSpecialTeamsJson) {
      TeamSPRatingSpecialTeamsObject <- jsonlite::fromJSON(TeamSPRatingSpecialTeamsJson)
      if (!is.null(TeamSPRatingSpecialTeamsObject$`rating`)) {
        self$`rating` <- TeamSPRatingSpecialTeamsObject$`rating`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rating": %s
        }',
        self$`rating`
      )
    },
    fromJSONString = function(TeamSPRatingSpecialTeamsJson) {
      TeamSPRatingSpecialTeamsObject <- jsonlite::fromJSON(TeamSPRatingSpecialTeamsJson)
      self$`rating` <- TeamSPRatingSpecialTeamsObject$`rating`
    }
  )
)
