# College Football Data API
#
# This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
#
# OpenAPI spec version: 2.3.5
# Contact: admin@collegefootballdata.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TeamSPRating Class
#'
#' @field year 
#' @field team 
#' @field conference 
#' @field rating 
#' @field ranking 
#' @field secondOrderWins 
#' @field sos 
#' @field offense 
#' @field defense 
#' @field specialTeams 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamSPRating <- R6::R6Class(
  'TeamSPRating',
  public = list(
    `year` = NULL,
    `team` = NULL,
    `conference` = NULL,
    `rating` = NULL,
    `ranking` = NULL,
    `secondOrderWins` = NULL,
    `sos` = NULL,
    `offense` = NULL,
    `defense` = NULL,
    `specialTeams` = NULL,
    initialize = function(`year`, `team`, `conference`, `rating`, `ranking`, `secondOrderWins`, `sos`, `offense`, `defense`, `specialTeams`){
      if (!missing(`year`)) {
        stopifnot(is.numeric(`year`), length(`year`) == 1)
        self$`year` <- `year`
      }
      if (!missing(`team`)) {
        stopifnot(is.character(`team`), length(`team`) == 1)
        self$`team` <- `team`
      }
      if (!missing(`conference`)) {
        stopifnot(is.character(`conference`), length(`conference`) == 1)
        self$`conference` <- `conference`
      }
      if (!missing(`rating`)) {
        self$`rating` <- `rating`
      }
      if (!missing(`ranking`)) {
        self$`ranking` <- `ranking`
      }
      if (!missing(`secondOrderWins`)) {
        self$`secondOrderWins` <- `secondOrderWins`
      }
      if (!missing(`sos`)) {
        self$`sos` <- `sos`
      }
      if (!missing(`offense`)) {
        stopifnot(R6::is.R6(`offense`))
        self$`offense` <- `offense`
      }
      if (!missing(`defense`)) {
        stopifnot(R6::is.R6(`defense`))
        self$`defense` <- `defense`
      }
      if (!missing(`specialTeams`)) {
        stopifnot(R6::is.R6(`specialTeams`))
        self$`specialTeams` <- `specialTeams`
      }
    },
    toJSON = function() {
      TeamSPRatingObject <- list()
      if (!is.null(self$`year`)) {
        TeamSPRatingObject[['year']] <- self$`year`
      }
      if (!is.null(self$`team`)) {
        TeamSPRatingObject[['team']] <- self$`team`
      }
      if (!is.null(self$`conference`)) {
        TeamSPRatingObject[['conference']] <- self$`conference`
      }
      if (!is.null(self$`rating`)) {
        TeamSPRatingObject[['rating']] <- self$`rating`
      }
      if (!is.null(self$`ranking`)) {
        TeamSPRatingObject[['ranking']] <- self$`ranking`
      }
      if (!is.null(self$`secondOrderWins`)) {
        TeamSPRatingObject[['secondOrderWins']] <- self$`secondOrderWins`
      }
      if (!is.null(self$`sos`)) {
        TeamSPRatingObject[['sos']] <- self$`sos`
      }
      if (!is.null(self$`offense`)) {
        TeamSPRatingObject[['offense']] <- self$`offense`$toJSON()
      }
      if (!is.null(self$`defense`)) {
        TeamSPRatingObject[['defense']] <- self$`defense`$toJSON()
      }
      if (!is.null(self$`specialTeams`)) {
        TeamSPRatingObject[['specialTeams']] <- self$`specialTeams`$toJSON()
      }

      TeamSPRatingObject
    },
    fromJSON = function(TeamSPRatingJson) {
      TeamSPRatingObject <- jsonlite::fromJSON(TeamSPRatingJson)
      if (!is.null(TeamSPRatingObject$`year`)) {
        self$`year` <- TeamSPRatingObject$`year`
      }
      if (!is.null(TeamSPRatingObject$`team`)) {
        self$`team` <- TeamSPRatingObject$`team`
      }
      if (!is.null(TeamSPRatingObject$`conference`)) {
        self$`conference` <- TeamSPRatingObject$`conference`
      }
      if (!is.null(TeamSPRatingObject$`rating`)) {
        self$`rating` <- TeamSPRatingObject$`rating`
      }
      if (!is.null(TeamSPRatingObject$`ranking`)) {
        self$`ranking` <- TeamSPRatingObject$`ranking`
      }
      if (!is.null(TeamSPRatingObject$`secondOrderWins`)) {
        self$`secondOrderWins` <- TeamSPRatingObject$`secondOrderWins`
      }
      if (!is.null(TeamSPRatingObject$`sos`)) {
        self$`sos` <- TeamSPRatingObject$`sos`
      }
      if (!is.null(TeamSPRatingObject$`offense`)) {
        offenseObject <- TeamSPRatingOffense$new()
        offenseObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$offense, auto_unbox = TRUE))
        self$`offense` <- offenseObject
      }
      if (!is.null(TeamSPRatingObject$`defense`)) {
        defenseObject <- TeamSPRatingDefense$new()
        defenseObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$defense, auto_unbox = TRUE))
        self$`defense` <- defenseObject
      }
      if (!is.null(TeamSPRatingObject$`specialTeams`)) {
        specialTeamsObject <- TeamSPRatingSpecialTeams$new()
        specialTeamsObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$specialTeams, auto_unbox = TRUE))
        self$`specialTeams` <- specialTeamsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "year": %d,
           "team": %s,
           "conference": %s,
           "rating": %s,
           "ranking": %s,
           "secondOrderWins": %s,
           "sos": %s,
           "offense": %s,
           "defense": %s,
           "specialTeams": %s
        }',
        self$`year`,
        self$`team`,
        self$`conference`,
        self$`rating`,
        self$`ranking`,
        self$`secondOrderWins`,
        self$`sos`,
        self$`offense`$toJSON(),
        self$`defense`$toJSON(),
        self$`specialTeams`$toJSON()
      )
    },
    fromJSONString = function(TeamSPRatingJson) {
      TeamSPRatingObject <- jsonlite::fromJSON(TeamSPRatingJson)
      self$`year` <- TeamSPRatingObject$`year`
      self$`team` <- TeamSPRatingObject$`team`
      self$`conference` <- TeamSPRatingObject$`conference`
      self$`rating` <- TeamSPRatingObject$`rating`
      self$`ranking` <- TeamSPRatingObject$`ranking`
      self$`secondOrderWins` <- TeamSPRatingObject$`secondOrderWins`
      self$`sos` <- TeamSPRatingObject$`sos`
      TeamSPRatingOffenseObject <- TeamSPRatingOffense$new()
      self$`offense` <- TeamSPRatingOffenseObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$offense, auto_unbox = TRUE))
      TeamSPRatingDefenseObject <- TeamSPRatingDefense$new()
      self$`defense` <- TeamSPRatingDefenseObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$defense, auto_unbox = TRUE))
      TeamSPRatingSpecialTeamsObject <- TeamSPRatingSpecialTeams$new()
      self$`specialTeams` <- TeamSPRatingSpecialTeamsObject$fromJSON(jsonlite::toJSON(TeamSPRatingObject$specialTeams, auto_unbox = TRUE))
    }
  )
)
